CREATE TABLE IF NOT EXISTS `reg` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Lat` varchar(50) NOT NULL DEFAULT '8.888050',
  `Lng` varchar(50) NOT NULL DEFAULT '-75.787003',
  `Pos` varchar(256) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
